development:
  adapter: mysql2
  encoding: utf8
  database: shorner_url
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: shorner_url
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: shorner_url
  pool: 5
  username: root
  password: